# Generated by Django 4.1.2 on 2022-11-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_member_city_member_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='No name', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(default='No name', max_length=200),
        ),
    ]
